
export const INIT_CRYPTOMARKET = 'INIT_CRYPTOMARKET';
export const UPDATE_CRYPTOMARKET = 'UPDATE_CRYPTOMARKET';
export const UPDATE_QUANTITYMARK = 'UPDATE_QUANTITYMARK';
export const RESET_QUANTITYMARK = 'RESET_QUANTITYMARK';