
export const INIT_USER = 'INIT_USER';
export const ADD_BUYPOWER = 'ADD_BUYPOWER';
export const BUY_CRYPTO = 'BUY_CRYPTO';
export const SELL_CRYPTO = 'SELL_CRYPTO';
export const UPDATE_VIRTUALMONEY = 'UPDATE_VIRTUALMONEY'
